# handler: prince or weasyprint # uncomment will overwrite HANDLER environment variable
prince:
  media:   "print"
  baseurl: "http://localhost"
weasyprint:
  media-type: "print"
  base-url: "http://localhost"
